// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    info: ['info'],
    identify: ['identify', 'auth'],
    logout: ['logout'],
    register: ['register'],
    drop: ['drop'],
    verify: ['verify register', 'confirm'],
    setPassword: ['set password']
  };

}).call(this);
